{{- if .Values.metadataSync.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: streaming-proof-metadata-sync
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "streaming-proof.labels" . | nindent 4 }}
{{- end }}
