{{- if and .Values.metadataSync.enabled .Values.metadataSync.sourceNamespace }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: streaming-proof-metadata-sync-source
  namespace: {{ .Values.metadataSync.sourceNamespace }}
  labels:
    {{- include "streaming-proof.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: streaming-proof-metadata-sync
    namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: streaming-proof-metadata-sync-source
{{- end }}
